service: serverless-stepf-cloudwatch-trigger
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1

functions:
  handler:
    handler: functions/handler.handler
